// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct VaraEthDemoClientProgram;
impl sails_rs::client::Program for VaraEthDemoClientProgram {}
pub trait VaraEthDemoClient {
    type Env: sails_rs::client::GearEnv;
    fn counter(&self) -> sails_rs::client::Service<counter::CounterImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> VaraEthDemoClient
    for sails_rs::client::Actor<VaraEthDemoClientProgram, E>
{
    type Env = E;
    fn counter(&self) -> sails_rs::client::Service<counter::CounterImpl, Self::Env> {
        self.service(stringify!(Counter))
    }
}
pub trait VaraEthDemoClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn init(
        self,
        counter: u32,
    ) -> sails_rs::client::PendingCtor<VaraEthDemoClientProgram, io::Init, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> VaraEthDemoClientCtors
    for sails_rs::client::Deployment<VaraEthDemoClientProgram, E>
{
    type Env = E;
    fn init(
        self,
        counter: u32,
    ) -> sails_rs::client::PendingCtor<VaraEthDemoClientProgram, io::Init, Self::Env> {
        self.pending_ctor((counter,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Init (counter: u32) -> ());
}

pub mod counter {
    use super::*;
    pub trait Counter {
        type Env: sails_rs::client::GearEnv;
        fn add(&mut self, value: u32) -> sails_rs::client::PendingCall<io::Add, Self::Env>;
        fn sub(&mut self, value: u32) -> sails_rs::client::PendingCall<io::Sub, Self::Env>;
        fn value(&self) -> sails_rs::client::PendingCall<io::Value, Self::Env>;
    }
    pub struct CounterImpl;
    impl<E: sails_rs::client::GearEnv> Counter for sails_rs::client::Service<CounterImpl, E> {
        type Env = E;
        fn add(&mut self, value: u32) -> sails_rs::client::PendingCall<io::Add, Self::Env> {
            self.pending_call((value,))
        }
        fn sub(&mut self, value: u32) -> sails_rs::client::PendingCall<io::Sub, Self::Env> {
            self.pending_call((value,))
        }
        fn value(&self) -> sails_rs::client::PendingCall<io::Value, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Add (value: u32) -> u32);
        sails_rs::io_struct_impl!(Sub (value: u32) -> u32);
        sails_rs::io_struct_impl!(Value () -> u32);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum CounterEvents {
            Added {
                /// #[indexed]
                source: ActorId,
                value: u32,
            },
            Subtracted {
                /// #[indexed]
                source: ActorId,
                value: u32,
            },
        }
        impl sails_rs::client::Event for CounterEvents {
            const EVENT_NAMES: &'static [Route] = &["Added", "Subtracted"];
        }
        impl sails_rs::client::ServiceWithEvents for CounterImpl {
            type Event = CounterEvents;
        }
    }
}
